export default {
    ADD_PROFILE: 'ADD_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    DELETE_PROFILE: 'DELETE_PROFILE',
    FETCH_DATA_OK: 'FETCH_DATA_OK',
    FETCH_DATA_BEGIN: 'FETCH_DATA_BEGIN',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
    SAVE_DATA_BEGIN: 'SAVE_DATA_BEGIN',
    SAVE_DATA_OK: 'SAVE_DATA_OK',
    SAVE_DATA_ERROR: 'SAVE_DATA_ERROR'
};
